apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      project: bank-hosting

  template:
    metadata:
      labels:
        project: bank-hosting

    spec:
      containers:
        - name: container-banking
          image: trickyknight0/banking-app:latest
          ports:
            - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: banking-service

spec:
  selector:
    project: bank-hosting
  ports:
    - port: 80
      targetPort: 8091
  type: NodePort
